"""domain core events fields registrations bot_dialogs media

Revision ID: e21d0036ee94
Revises: 0001
Create Date: 2026-05-14 13:25:36.958581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.Enum('OPEN_DAY', 'MASTER_CLASS', 'OLYMPIAD', 'CONSULTATION', 'OTHER', name='event_type'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', 'ARCHIVED', name='event_status'), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('waitlist_enabled', sa.Boolean(), nullable=False),
    sa.Column('moderation_required', sa.Boolean(), nullable=False),
    sa.Column('registration_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('registration_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cover_media_id', sa.String(length=36), nullable=True),
    sa.Column('reminder_offsets_minutes', sa.JSON(), nullable=False),
    sa.Column('confirmation_template', sa.Text(), nullable=True),
    sa.Column('max_chat_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_starts_at'), 'events', ['starts_at'], unique=False)
    op.create_index(op.f('ix_events_status'), 'events', ['status'], unique=False)
    op.create_index(op.f('ix_events_title'), 'events', ['title'], unique=False)
    op.create_table('bot_dialogs',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.Enum('IDLE', 'ASKING_FIELD', 'CONFIRMING', 'DONE', name='dialog_state'), nullable=False),
    sa.Column('current_field_index', sa.Integer(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'event_id', name='uq_dialog_user_event')
    )
    op.create_index(op.f('ix_bot_dialogs_event_id'), 'bot_dialogs', ['event_id'], unique=False)
    op.create_index(op.f('ix_bot_dialogs_user_id'), 'bot_dialogs', ['user_id'], unique=False)
    op.create_table('event_fields',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('placeholder', sa.String(length=255), nullable=True),
    sa.Column('hint', sa.String(length=500), nullable=True),
    sa.Column('field_type', sa.Enum('TEXT', 'TEXTAREA', 'EMAIL', 'PHONE', 'NUMBER', 'DATE', 'SELECT', 'MULTI_SELECT', 'CONSENT', name='field_type'), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_fields_event_id'), 'event_fields', ['event_id'], unique=False)
    op.create_table('media_files',
    sa.Column('kind', sa.Enum('EVENT_COVER', 'EVENT_GALLERY', 'BROADCAST_IMAGE', 'BRANDING', name='media_kind'), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('uploader_id', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('mime', sa.String(length=64), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sha256', sa.LargeBinary(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploader_id'], ['admin_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_media_sha256', 'media_files', ['sha256'], unique=True)
    op.create_table('registrations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'WAITLIST', 'CANCELLED', 'REJECTED', name='registration_status'), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('waitlist_position', sa.Integer(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('checked_in_by', sa.Uuid(), nullable=True),
    sa.Column('checked_in_qr_bucket', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_reason', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['checked_in_by'], ['admin_accounts.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registrations_event_id'), 'registrations', ['event_id'], unique=False)
    op.create_index('ix_registrations_event_status', 'registrations', ['event_id', 'status'], unique=False)
    op.create_index(op.f('ix_registrations_user_id'), 'registrations', ['user_id'], unique=False)
    op.create_index('uq_active_registration_per_user_event', 'registrations', ['user_id', 'event_id'], unique=True, postgresql_where=sa.text("status IN ('CONFIRMED', 'WAITLIST', 'PENDING')"))
    op.create_table('max_attachment_tokens',
    sa.Column('media_file_id', sa.Uuid(), nullable=False),
    sa.Column('max_token', sa.String(length=500), nullable=False),
    sa.Column('max_url', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refreshed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('media_file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('max_attachment_tokens')
    op.drop_index('uq_active_registration_per_user_event', table_name='registrations', postgresql_where=sa.text("status IN ('CONFIRMED', 'WAITLIST', 'PENDING')"))
    op.drop_index(op.f('ix_registrations_user_id'), table_name='registrations')
    op.drop_index('ix_registrations_event_status', table_name='registrations')
    op.drop_index(op.f('ix_registrations_event_id'), table_name='registrations')
    op.drop_table('registrations')
    op.drop_index('ux_media_sha256', table_name='media_files')
    op.drop_table('media_files')
    op.drop_index(op.f('ix_event_fields_event_id'), table_name='event_fields')
    op.drop_table('event_fields')
    op.drop_index(op.f('ix_bot_dialogs_user_id'), table_name='bot_dialogs')
    op.drop_index(op.f('ix_bot_dialogs_event_id'), table_name='bot_dialogs')
    op.drop_table('bot_dialogs')
    op.drop_index(op.f('ix_events_title'), table_name='events')
    op.drop_index(op.f('ix_events_status'), table_name='events')
    op.drop_index(op.f('ix_events_starts_at'), table_name='events')
    op.drop_table('events')
    # drop custom enum types
    sa.Enum(name='registration_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='media_kind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='field_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='dialog_state').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='event_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='event_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
